# Generated by Django 5.2.1 on 2025-05-31 02:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dispositivo', models.CharField(max_length=100, unique=True)),
                ('id_dispositivo_fiware', models.CharField(help_text='ID único do dispositivo no Fiware Orion', max_length=100, unique=True)),
                ('localizacao_latitude', models.FloatField(blank=True, null=True)),
                ('localizacao_longitude', models.FloatField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: UmidadeSolo, TemperaturaAr, waterLevel', max_length=50, unique=True)),
                ('unidade_medida', models.CharField(help_text='Ex: %, °C, cm', max_length=20)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeituraSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('timestamp_leitura', models.DateTimeField(help_text='Timestamp da leitura original no dispositivo')),
                ('timestamp_recebimento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='sensores.dispositivo')),
                ('tipo_sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='sensores.tiposensor')),
            ],
            options={
                'ordering': ['-timestamp_leitura'],
            },
        ),
    ]
